name: Upload Airflow script to GCP bucket
on:
  push:
    branches:
    - main

jobs:
  upload_spark_script:
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: auth
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/699252083022/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider'
        service_account: 'github-actions-service-account@gcp-demo-398309.iam.gserviceaccount.com'

    - name: upload-file
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'airflow/hello_world.py'
        destination: 'us-central1-cloud-composer--11dee88b-bucket/dags/'